import { StyleSheet, Platform } from "react-native";

export const sidebarStyles = StyleSheet.create({
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
  },
  sidebar: {
    position: "absolute",
    right: 0,
    top: Platform.OS === "ios" ? 120 : 90,
    bottom: 30,
    width: 200,
    backgroundColor: "white",
    padding: 10,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: -2, height: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  sidebarTitle: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 8,
  },
  filterRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 10,
  },
  filterButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#9ca3af",
    backgroundColor: "#f3f4f6",
    borderRadius: 6,
    paddingVertical: 5,
    alignItems: "center",
  },
  filterButtonActive: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#2563eb",
    backgroundColor: "#2563eb",
    borderRadius: 6,
    paddingVertical: 5,
    alignItems: "center",
  },
  filterButtonText: {
    color: "#1f2937",
    fontWeight: "600",
    fontSize: 12,
  },
  filterIcon: {
    fontSize: 12,
    marginBottom: 1,
  },
  filterButtonTextActive: {
    color: "white",
    fontWeight: "700",
    fontSize: 12,
  },
  itemsList: {
    flex: 1,
  },
  buttonRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 10,
    paddingBottom: 20,
  },
  exportButton: {
    flex: 1,
    backgroundColor: "#27ae60",
    padding: 12,
    borderRadius: 5,
    alignItems: "center",
  },
  importButton: {
    flex: 1,
    backgroundColor: "#3498db",
    padding: 12,
    borderRadius: 5,
    alignItems: "center",
  },
  exportText: {
    color: "white",
    fontWeight: "bold",
  },
});
